name: BreweryxJobs
version: '1.0-SNAPSHOT'
main: me.grahamwilk.breweryxjobs.BreweryxJobs
api-version: '1.21'
commands:
  barkeepersellmenu:
    description: Opens up the menu to sell brews for the barkeeper job.
    usage: /barkeepersellmenu

